### ISSUE TITLE
Script is assuming, not verifying

### ISSUE THREAD

**Issue by Czino** [madumas/ethsupply#4]
The script only assumes that certain amount of ETH has been issued while ignoring transactions and account balances.

If an account balance was edited, this script would not catch it.

**Comment by madumas** [comment]
The script calculates the issuance based on Ethereum whitepaper, and relevant EIPs that make the protocol specification. Another script could be written to sum all the account balances, but this is not necessary because a node software that would not follow the protocol spec would fork itself out. All Ethereum node implementations (including geth, openethereum/parity and nethermind) are on agreement.

**Comment by madumas** [comment]
To determine the amount of Eth that exists, checkout Nethermind's SupplyVerifier script. This method has the advantage of taking into account Eth destroyed by selfdestruct() with balances sent to self, and by traversing the complete Merkle tree should convince the most skeptical.
